name: Generate attestation libraries
on:
  push:
    branches:
      - "main"
  schedule:
    # There are two reasons we may need to regenerate libraries.
    # First, there's an explicit change merged into main. That's caught by the
    # other trigger. The second reason is when protoc is updated to a newer
    # version (still within the versions specified here, as 3.x may map to 3.20
    # instead of 3.19) without any changes to the main branch of this
    # repository. For this reason, the second trigger runs this workflow once a
    # week.
    - cron: '0 14 * * 1'
jobs:
  run-make-protos:
    runs-on: ubuntu-latest
    steps:
      - name: Install protoc
        uses: arduino/setup-protoc@9b1ee5b22b0a3f1feb8c2ff99b32c89b3c3191e9
        with:
          version: '23.x'
      - name: Install Go
        uses: actions/setup-go@fac708d6674e30b6ba41289acaab6d4b75aa0753
        with:
          go-version: 1.20.x
      - name: setup env
        run: |
          echo "$(go env GOPATH)/bin" >> $GITHUB_PATH
      - name: Checkout repo
        uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9
      - name: Generate libraries
        run: |
          make protos
      - name: Create PR
        # This step opens a PR if make protos resulted in a difference from
        # what's currently in the main branch. It has no permissions to write to
        # the repository, maintainers are required to approve and merge the PRs.
        uses: peter-evans/create-pull-request@284f54f989303d2699d373481a0cfa13ad5a6666
        with:
          commit-message: Regenerate attestation libraries
          title: Regenerate attestation libraries
          body: This PR updates the attestation libraries generated using protoc.
          base: main
          branch: actions-regenerate-attestation-libraries
          delete-branch: true
          signoff: true
          author: GitHub <noreply@github.com>
          committer: GitHub <noreply@github.com>
