name: Run Go tests
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'go/**'
  # Want to trigger these tests whenever the attestation
  # libraries are regenerated, or new modules/tests are
  # added to the language bindings
  pull_request:
      paths:
          - 'go/**'
permissions: read-all
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11
      - name: Install Go
        uses: actions/setup-go@93397bea11091df50f3d7e59dc26a7711a8bcfbe
        with:
          go-version: 1.20.x
      - name: Format
        run: if [ "$(gofmt -s -l . | wc -l)" -gt 0 ]; then exit 1; fi
      - name: Setup Env
        run: |
          echo "$(go env GOPATH)/bin" >> $GITHUB_PATH
      - name: Run tests
        run: |
          make go_test
