name: Run Go tests
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'go/**'
  # Want to trigger these tests whenever the attestation
  # libraries are regenerated, or new modules/tests are
  # added to the language bindings
  pull_request:
      paths:
          - 'go/**'
permissions: read-all
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8
      - name: Install Go
        uses: actions/setup-go@4dc6199c7b1a012772edbd06daecab0f50c9053c
        with:
          go-version: 1.23.x
      - name: Format
        run: if [ "$(gofmt -s -l . | wc -l)" -gt 0 ]; then exit 1; fi
      - name: Setup Env
        run: |
          echo "$(go env GOPATH)/bin" >> $GITHUB_PATH
      - name: Run tests
        run: |
          make go_test
